if(EXISTS "/home/henry/sync/codingProjects/learning_cpp/chessClone/build-release/tests/unit_tests_tests-b12d07c.cmake")
  include("/home/henry/sync/codingProjects/learning_cpp/chessClone/build-release/tests/unit_tests_tests-b12d07c.cmake")
else()
  add_test(unit_tests_NOT_BUILT-b12d07c unit_tests_NOT_BUILT-b12d07c)
endif()
