# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/5bn5f4ivqf4xn19khh4kcg4ngnjs6spg-cmake-4.1.2/bin/cmake

# The command to remove a file.
RM = /nix/store/5bn5f4ivqf4xn19khh4kcg4ngnjs6spg-cmake-4.1.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quartz/sync/codingProjects/learning_cpp/chessClone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quartz/sync/codingProjects/learning_cpp/chessClone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/5bn5f4ivqf4xn19khh4kcg4ngnjs6spg-cmake-4.1.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/5bn5f4ivqf4xn19khh4kcg4ngnjs6spg-cmake-4.1.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quartz/sync/codingProjects/learning_cpp/chessClone/CMakeFiles /home/quartz/sync/codingProjects/learning_cpp/chessClone//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quartz/sync/codingProjects/learning_cpp/chessClone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gui_chess_game

# Build rule for target.
gui_chess_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gui_chess_game
.PHONY : gui_chess_game

# fast build rule for target.
gui_chess_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui_chess_game.dir/build.make CMakeFiles/gui_chess_game.dir/build
.PHONY : gui_chess_game/fast

#=============================================================================
# Target rules for targets named pertree_debugger

# Build rule for target.
pertree_debugger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pertree_debugger
.PHONY : pertree_debugger

# fast build rule for target.
pertree_debugger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pertree_debugger.dir/build.make CMakeFiles/pertree_debugger.dir/build
.PHONY : pertree_debugger/fast

#=============================================================================
# Target rules for targets named chessBoard

# Build rule for target.
chessBoard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chessBoard
.PHONY : chessBoard

# fast build rule for target.
chessBoard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessBoard.dir/build.make CMakeFiles/chessBoard.dir/build
.PHONY : chessBoard/fast

#=============================================================================
# Target rules for targets named timer

# Build rule for target.
timer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timer
.PHONY : timer

# fast build rule for target.
timer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/build
.PHONY : timer/fast

#=============================================================================
# Target rules for targets named pieceMovements

# Build rule for target.
pieceMovements: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pieceMovements
.PHONY : pieceMovements

# fast build rule for target.
pieceMovements/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pieceMovements.dir/build.make CMakeFiles/pieceMovements.dir/build
.PHONY : pieceMovements/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

src-gui-game/imgui-sfml/imgui-SFML.o: src-gui-game/imgui-sfml/imgui-SFML.cpp.o
.PHONY : src-gui-game/imgui-sfml/imgui-SFML.o

# target to build an object file
src-gui-game/imgui-sfml/imgui-SFML.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui_chess_game.dir/build.make CMakeFiles/gui_chess_game.dir/src-gui-game/imgui-sfml/imgui-SFML.cpp.o
.PHONY : src-gui-game/imgui-sfml/imgui-SFML.cpp.o

src-gui-game/imgui-sfml/imgui-SFML.i: src-gui-game/imgui-sfml/imgui-SFML.cpp.i
.PHONY : src-gui-game/imgui-sfml/imgui-SFML.i

# target to preprocess a source file
src-gui-game/imgui-sfml/imgui-SFML.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui_chess_game.dir/build.make CMakeFiles/gui_chess_game.dir/src-gui-game/imgui-sfml/imgui-SFML.cpp.i
.PHONY : src-gui-game/imgui-sfml/imgui-SFML.cpp.i

src-gui-game/imgui-sfml/imgui-SFML.s: src-gui-game/imgui-sfml/imgui-SFML.cpp.s
.PHONY : src-gui-game/imgui-sfml/imgui-SFML.s

# target to generate assembly for a file
src-gui-game/imgui-sfml/imgui-SFML.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui_chess_game.dir/build.make CMakeFiles/gui_chess_game.dir/src-gui-game/imgui-sfml/imgui-SFML.cpp.s
.PHONY : src-gui-game/imgui-sfml/imgui-SFML.cpp.s

src-gui-game/main.o: src-gui-game/main.cpp.o
.PHONY : src-gui-game/main.o

# target to build an object file
src-gui-game/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui_chess_game.dir/build.make CMakeFiles/gui_chess_game.dir/src-gui-game/main.cpp.o
.PHONY : src-gui-game/main.cpp.o

src-gui-game/main.i: src-gui-game/main.cpp.i
.PHONY : src-gui-game/main.i

# target to preprocess a source file
src-gui-game/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui_chess_game.dir/build.make CMakeFiles/gui_chess_game.dir/src-gui-game/main.cpp.i
.PHONY : src-gui-game/main.cpp.i

src-gui-game/main.s: src-gui-game/main.cpp.s
.PHONY : src-gui-game/main.s

# target to generate assembly for a file
src-gui-game/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui_chess_game.dir/build.make CMakeFiles/gui_chess_game.dir/src-gui-game/main.cpp.s
.PHONY : src-gui-game/main.cpp.s

src-lib/chessBoard.o: src-lib/chessBoard.cpp.o
.PHONY : src-lib/chessBoard.o

# target to build an object file
src-lib/chessBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessBoard.dir/build.make CMakeFiles/chessBoard.dir/src-lib/chessBoard.cpp.o
.PHONY : src-lib/chessBoard.cpp.o

src-lib/chessBoard.i: src-lib/chessBoard.cpp.i
.PHONY : src-lib/chessBoard.i

# target to preprocess a source file
src-lib/chessBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessBoard.dir/build.make CMakeFiles/chessBoard.dir/src-lib/chessBoard.cpp.i
.PHONY : src-lib/chessBoard.cpp.i

src-lib/chessBoard.s: src-lib/chessBoard.cpp.s
.PHONY : src-lib/chessBoard.s

# target to generate assembly for a file
src-lib/chessBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessBoard.dir/build.make CMakeFiles/chessBoard.dir/src-lib/chessBoard.cpp.s
.PHONY : src-lib/chessBoard.cpp.s

src-lib/pieceMovements.o: src-lib/pieceMovements.cpp.o
.PHONY : src-lib/pieceMovements.o

# target to build an object file
src-lib/pieceMovements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pieceMovements.dir/build.make CMakeFiles/pieceMovements.dir/src-lib/pieceMovements.cpp.o
.PHONY : src-lib/pieceMovements.cpp.o

src-lib/pieceMovements.i: src-lib/pieceMovements.cpp.i
.PHONY : src-lib/pieceMovements.i

# target to preprocess a source file
src-lib/pieceMovements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pieceMovements.dir/build.make CMakeFiles/pieceMovements.dir/src-lib/pieceMovements.cpp.i
.PHONY : src-lib/pieceMovements.cpp.i

src-lib/pieceMovements.s: src-lib/pieceMovements.cpp.s
.PHONY : src-lib/pieceMovements.s

# target to generate assembly for a file
src-lib/pieceMovements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pieceMovements.dir/build.make CMakeFiles/pieceMovements.dir/src-lib/pieceMovements.cpp.s
.PHONY : src-lib/pieceMovements.cpp.s

src-lib/timer.o: src-lib/timer.cpp.o
.PHONY : src-lib/timer.o

# target to build an object file
src-lib/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src-lib/timer.cpp.o
.PHONY : src-lib/timer.cpp.o

src-lib/timer.i: src-lib/timer.cpp.i
.PHONY : src-lib/timer.i

# target to preprocess a source file
src-lib/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src-lib/timer.cpp.i
.PHONY : src-lib/timer.cpp.i

src-lib/timer.s: src-lib/timer.cpp.s
.PHONY : src-lib/timer.s

# target to generate assembly for a file
src-lib/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src-lib/timer.cpp.s
.PHONY : src-lib/timer.cpp.s

src-perftree-debugger/main.o: src-perftree-debugger/main.cpp.o
.PHONY : src-perftree-debugger/main.o

# target to build an object file
src-perftree-debugger/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pertree_debugger.dir/build.make CMakeFiles/pertree_debugger.dir/src-perftree-debugger/main.cpp.o
.PHONY : src-perftree-debugger/main.cpp.o

src-perftree-debugger/main.i: src-perftree-debugger/main.cpp.i
.PHONY : src-perftree-debugger/main.i

# target to preprocess a source file
src-perftree-debugger/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pertree_debugger.dir/build.make CMakeFiles/pertree_debugger.dir/src-perftree-debugger/main.cpp.i
.PHONY : src-perftree-debugger/main.cpp.i

src-perftree-debugger/main.s: src-perftree-debugger/main.cpp.s
.PHONY : src-perftree-debugger/main.s

# target to generate assembly for a file
src-perftree-debugger/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pertree_debugger.dir/build.make CMakeFiles/pertree_debugger.dir/src-perftree-debugger/main.cpp.s
.PHONY : src-perftree-debugger/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... chessBoard"
	@echo "... gui_chess_game"
	@echo "... pertree_debugger"
	@echo "... pieceMovements"
	@echo "... timer"
	@echo "... src-gui-game/imgui-sfml/imgui-SFML.o"
	@echo "... src-gui-game/imgui-sfml/imgui-SFML.i"
	@echo "... src-gui-game/imgui-sfml/imgui-SFML.s"
	@echo "... src-gui-game/main.o"
	@echo "... src-gui-game/main.i"
	@echo "... src-gui-game/main.s"
	@echo "... src-lib/chessBoard.o"
	@echo "... src-lib/chessBoard.i"
	@echo "... src-lib/chessBoard.s"
	@echo "... src-lib/pieceMovements.o"
	@echo "... src-lib/pieceMovements.i"
	@echo "... src-lib/pieceMovements.s"
	@echo "... src-lib/timer.o"
	@echo "... src-lib/timer.i"
	@echo "... src-lib/timer.s"
	@echo "... src-perftree-debugger/main.o"
	@echo "... src-perftree-debugger/main.i"
	@echo "... src-perftree-debugger/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

