add_test( [==[Addition works correctly, hello world]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[Addition works correctly\, hello world]==]  )
set_tests_properties( [==[Addition works correctly, hello world]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
add_test( [==[Valid initialization]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[Valid initialization]==]  )
set_tests_properties( [==[Valid initialization]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
add_test( [==[Invalid initialization with too high top index]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[Invalid initialization with too high top index]==]  )
set_tests_properties( [==[Invalid initialization with too high top index]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
add_test( [==[Push elements works until full]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[Push elements works until full]==]  )
set_tests_properties( [==[Push elements works until full]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
add_test( [==[Pop element returns the correct value]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[Pop element returns the correct value]==]  )
set_tests_properties( [==[Pop element returns the correct value]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
add_test( [==[Pop from empty stack throws underflow]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[Pop from empty stack throws underflow]==]  )
set_tests_properties( [==[Pop from empty stack throws underflow]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
add_test( [==[PushItems with array works correctly]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[PushItems with array works correctly]==]  )
set_tests_properties( [==[PushItems with array works correctly]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
add_test( [==[PushItems with another stackStack works correctly]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[PushItems with another stackStack works correctly]==]  )
set_tests_properties( [==[PushItems with another stackStack works correctly]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
add_test( [==[test individual pawn moves]==] /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests/unit_tests [==[test individual pawn moves]==]  )
set_tests_properties( [==[test individual pawn moves]==] PROPERTIES WORKING_DIRECTORY /home/henry/sync/codingProjects/learning_cpp/chessClone/build-debug/tests)
set( unit_tests_TESTS [==[Addition works correctly, hello world]==] [==[Valid initialization]==] [==[Invalid initialization with too high top index]==] [==[Push elements works until full]==] [==[Pop element returns the correct value]==] [==[Pop from empty stack throws underflow]==] [==[PushItems with array works correctly]==] [==[PushItems with another stackStack works correctly]==] [==[test individual pawn moves]==])
